//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTION
    {
        public int id { get; set; }
        public string collection_no { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public string sales_code { get; set; }
        public bool acknowledge { get; set; }
        public string acknowledge_by { get; set; }
        public Nullable<System.DateTime> acknowledged_date { get; set; }
        public string created_by { get; set; }
        public string area_name { get; set; }
    }
}
