//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public decimal CusID { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string CusSearchTerm { get; set; }
        public string CusAddress1 { get; set; }
        public string CusAddress2 { get; set; }
        public string CusAddress3 { get; set; }
        public string CusCity { get; set; }
        public string CusDeliveryPlant { get; set; }
        public string CusSalesOffice { get; set; }
        public string CusSODescription { get; set; }
        public string CusSalesGroup { get; set; }
        public string CusSGDescription { get; set; }
        public string CusREPCode { get; set; }
        public string CusREPFirstName { get; set; }
        public string CusREPLastName { get; set; }
        public string CusGroup { get; set; }
        public string CusContactPerson { get; set; }
        public string CusBusinessRegNo { get; set; }
        public string CusComments { get; set; }
        public string CusTelNo { get; set; }
        public string CusFaxNo { get; set; }
        public string CusStatus { get; set; }
        public string CompanyCode { get; set; }
        public byte[] CusTimeStamp { get; set; }
        public string CusSyncStatus { get; set; }
        public string CusCreatedDate { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    }
}
