//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOutstanding
    {
        public decimal OutID { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string CreditPeriod { get; set; }
        public string CreditLimit { get; set; }
        public string TotOutstanding { get; set; }
        public string CurrentValue { get; set; }
        public string C1_30Days { get; set; }
        public string C31_60Days { get; set; }
        public string C61_90Days { get; set; }
        public string C91_120Days { get; set; }
        public string C121_180Days { get; set; }
        public string C181_360Days { get; set; }
        public string Over361Days { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
