//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAP_SYSEntities : DbContext
    {
        public SAP_SYSEntities()
            : base("name=SAP_SYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<SalesOrderMaster> SalesOrderMasters { get; set; }
        public virtual DbSet<CustomerOutstanding> CustomerOutstandings { get; set; }
    }
}
