//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINANCE_MGR_SYSEntities : DbContext
    {
        public FINANCE_MGR_SYSEntities()
            : base("name=FINANCE_MGR_SYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentStatusLvlMaster> CurrentStatusLvlMasters { get; set; }
        public virtual DbSet<EnhancementTextMaster> EnhancementTextMasters { get; set; }
        public virtual DbSet<ReasonMaster> ReasonMasters { get; set; }
        public virtual DbSet<RequestDetail> RequestDetails { get; set; }
        public virtual DbSet<RequestHeader> RequestHeaders { get; set; }
        public virtual DbSet<RequestImage> RequestImages { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<vw_Requests> vw_Requests { get; set; }
    }
}
