//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Collection_SYSEntities : DbContext
    {
        public Collection_SYSEntities()
            : base("name=Collection_SYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLLECTION_TICKETS> COLLECTION_TICKETS { get; set; }
        public virtual DbSet<TICKET_MSGS> TICKET_MSGS { get; set; }
        public virtual DbSet<COLLECTION> COLLECTIONS { get; set; }
        public virtual DbSet<PAYED_INVOICES> PAYED_INVOICES { get; set; }
    
        public virtual int UpdateInvoiceAcknowledge(string invoice_id, Nullable<bool> state)
        {
            var invoice_idParameter = invoice_id != null ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateInvoiceAcknowledge", invoice_idParameter, stateParameter);
        }
    
        public virtual ObjectResult<FullCollectionData_Result> FullCollectionData(string collectionID)
        {
            var collectionIDParameter = collectionID != null ?
                new ObjectParameter("collectionID", collectionID) :
                new ObjectParameter("collectionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FullCollectionData_Result>("FullCollectionData", collectionIDParameter);
        }
    }
}
