//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CollectionSYSEntities : DbContext
    {
        public CollectionSYSEntities()
            : base("name=CollectionSYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLLECTION> COLLECTIONS { get; set; }
    
        public virtual ObjectResult<FullCollectionData_Result> FullCollectionData(string collectionID)
        {
            var collectionIDParameter = collectionID != null ?
                new ObjectParameter("collectionID", collectionID) :
                new ObjectParameter("collectionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FullCollectionData_Result>("FullCollectionData", collectionIDParameter);
        }
    }
}
