//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_CUS_PAINT_BRANDS
    {
        public int ID { get; set; }
        public Nullable<decimal> CusReqID { get; set; }
        public string PaintBrand { get; set; }
        public Nullable<decimal> StockVal { get; set; }
        public Nullable<decimal> MonthlyTOVal { get; set; }
    }
}
