//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_CUS_HEADER
    {
        public int CusReqID { get; set; }
        public string CurrentStat { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CusName { get; set; }
        public string CusAddress { get; set; }
        public string CusTel { get; set; }
        public string CusFax { get; set; }
        public string CusEmail { get; set; }
        public string DelAddress { get; set; }
        public string DelTel { get; set; }
        public string DelFax { get; set; }
        public string DelEmail { get; set; }
        public string SalesCode { get; set; }
        public string SalesAreaName { get; set; }
        public string VatRegNo { get; set; }
        public Nullable<System.DateTime> DateofInitialCusVisit { get; set; }
        public string PersonDealWith { get; set; }
        public string BusinessNature { get; set; }
        public string BusinessDuration { get; set; }
        public string Nature { get; set; }
        public string ContactNoPersonDealWith { get; set; }
        public string DesignationPersonDealWith { get; set; }
        public string BusinessArea { get; set; }
        public string BusinessPremises { get; set; }
        public string CusFinanceStability { get; set; }
        public string CusPayStrength { get; set; }
        public Nullable<decimal> InitialOrder { get; set; }
        public Nullable<decimal> FirstAvgSales { get; set; }
        public Nullable<decimal> NextAvgSales { get; set; }
        public Nullable<decimal> EstiPurchase { get; set; }
        public bool BusinessRegCert { get; set; }
        public bool VatRegCert { get; set; }
        public bool IDofOwner { get; set; }
        public bool Form20 { get; set; }
        public bool BankStatments { get; set; }
        public bool Business_Place { get; set; }
        public bool Application_Form { get; set; }
        public bool SVAT_Customer { get; set; }
        public bool SVAT_Validation { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
