//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYED_INVOICES
    {
        public int id { get; set; }
        public string collection_no { get; set; }
        public string payment_key { get; set; }
        public string invoice_no { get; set; }
        public string customer_id { get; set; }
        public string sales_code { get; set; }
        public Nullable<decimal> invoice_amount { get; set; }
        public Nullable<decimal> invoice_allocated { get; set; }
        public string payment_term { get; set; }
        public Nullable<decimal> os_balance { get; set; }
        public Nullable<int> nod { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> acknowledge { get; set; }
    }
}
