//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderMaster
    {
        public decimal DocID { get; set; }
        public string OrderType { get; set; }
        public string SalesOrg { get; set; }
        public string DChannel { get; set; }
        public string Division { get; set; }
        public string CusCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public string SAPDocID { get; set; }
        public string PaymentTerm { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string LockedBy { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Remarks { get; set; }
        public string AreaName { get; set; }
        public string VisitStatus { get; set; }
        public string DeliveryNote { get; set; }
        public string SalesCode { get; set; }
        public string AddDiscount { get; set; }
        public string OrderCategory { get; set; }
        public string OrderText { get; set; }
        public string KeyState { get; set; }
        public string CusDisGroup { get; set; }
        public string OrderReason { get; set; }
    }
}
