//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_MSGS
    {
        public int msg_id { get; set; }
        public Nullable<int> ticket_id { get; set; }
        public string msg { get; set; }
        public string msg_from { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
