//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.PORTAL.dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Requests
    {
        public decimal ReqID { get; set; }
        public Nullable<decimal> AllowCreditLimit { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreditLimit { get; set; }
        public string SalesCode { get; set; }
        public string CusName { get; set; }
        public Nullable<decimal> CusCode { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public string InitialComment { get; set; }
        public string StatusText { get; set; }
        public Nullable<int> size_ { get; set; }
        public Nullable<int> CurrentStatusLevel { get; set; }
        public string ReqStatus { get; set; }
        public string FileName { get; set; }
        public string RequestType { get; set; }
        public string CusSGDescription { get; set; }
        public Nullable<decimal> CreditExposure { get; set; }
        public string RecentAction { get; set; }
        public Nullable<decimal> SAPupdateAmount { get; set; }
    }
}
